version: "3.8"

services:
    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:latest
        volumes:
            - ./nginx/conf.prod/:/etc/nginx/conf.d/:ro
            - /certbot/www:/var/www/certbot/
            - /certbot/conf/:/etc/nginx/ssl/
        ports:
            - 80:80
            - 443:443
        depends_on:
            - next
            - wordpress

    certbot:
        image: certbot/certbot:latest
        volumes:
            - /certbot/www/:/var/www/certbot/
            - /certbot/conf/:/etc/letsencrypt/

    next:
        container_name: ${PROJECT_NAME}-next
        build:
            context: ./next
            dockerfile: Dockerfile.prod
        volumes:
            - ./next:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        ports:
            - "3000:3000"
        depends_on:
            - wordpress

    wordpress:
        container_name: ${PROJECT_NAME}-wordpress
        image: wordpress
        restart: always
        env_file:
            - ./.env
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        # Hide wordpress behind "/admin" subdirectory
        # to make it harder to reach by hackers.
        working_dir: /var/www/html/admin
        volumes:
            - ./wordpress/plugins:/var/www/html/admin/wp-content/plugins
            - ./wordpress/themes:/var/www/html/admin/wp-content/themes:ro
            - ./wordpress/uploads:/var/www/html/admin/wp-content/uploads
            - ./wordpress/languages:/var/www/html/admin/wp-content/languages
        depends_on:
            - db
        ports:
            - 8080:80

    db:
        container_name: ${PROJECT_NAME}-db
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
        volumes:
            - /db:/var/lib/mysql

volumes:
    db:
    wordpress:
